DROP DATABASE IF EXISTS chinook;

CREATE DATABASE chinook;

USE chinook;

CREATE TABLE media_type (
	media_type_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120)
);

CREATE TABLE genre (
	genre_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120)
);

CREATE TABLE playlist (
	playlist_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120)
);

CREATE TABLE playlist_track (
	playlist_id INT UNSIGNED NOT NULL,
	track_id INT UNSIGNED NOT NULL,
    PRIMARY KEY(playlist_id, track_id)
);

CREATE TABLE artist (
	artist_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120)
);

CREATE TABLE album (
	album_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(160),
    artist_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (artist_id)
		REFERENCES artist(artist_id)
        ON DELETE CASCADE
);

CREATE TABLE track (
	track_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200),
    album_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (album_id)
		REFERENCES album(album_id)
        ON DELETE CASCADE,
	media_type_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (media_type_id)
		REFERENCES media_type(media_type_id)
        ON DELETE CASCADE,
	genre_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (genre_id)
		REFERENCES genre(genre_id)
        ON DELETE CASCADE,
	composer VARCHAR(220),
    milliseconds INT,
    bytes INT,
    unit_price FLOAT
);

CREATE TABLE employee (
	employee_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(20),
    first_name VARCHAR(20),
    title VARCHAR(30),
    -- reports_to INT UNSIGNED,
--     FOREIGN KEY (employee_id)
-- 		REFERENCES employee(employee_id)
--         ON DELETE CASCADE,
    birth_date DATETIME,
    hire_date DATETIME,
    address_1 VARCHAR(50),
    address_2 VARCHAR(50),
    city VARCHAR(40),
    state VARCHAR(40),
    country VARCHAR(40),
    postal_code VARCHAR(10),
    phone VARCHAR(24),
    email VARCHAR(60)
);

CREATE TABLE customer(
	customer_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    company VARCHAR(80),
    address_1 VARCHAR(50),
    address_2 VARCHAR(50),
    city VARCHAR(40),
    state VARCHAR(40),
    country VARCHAR(40),
    postal_code VARCHAR(10),
    phone VARCHAR(24),
    email VARCHAR(60),
    support_rep_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (support_rep_id)
		REFERENCES employee(employee_id)
        ON DELETE CASCADE
);

CREATE TABLE invoice(
	invoice_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    customer_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (customer_id)
		REFERENCES customer(customer_id)
        ON DELETE CASCADE,
	invoice_date DATETIME,
    billing_address_1 VARCHAR(50),
    billing_address_2 VARCHAR(50),
    billing_city VARCHAR(40),
    billing_state VARCHAR(40),
    billing_country VARCHAR(40),
    billing_postal_code VARCHAR(10),
    total FLOAT
);

CREATE TABLE invoice_item(
	invoice_item_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (invoice_id)
		REFERENCES invoice(invoice_id)
        ON DELETE CASCADE,
	track_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (track_id)
		REFERENCES track(track_id)
		ON DELETE CASCADE,
	unit_price FLOAT,
    quantity INT
);

INSERT INTO media_type VALUES
	(NULL, 'MPEG audio file'),
    (NULL, 'Protected AAC audio file'),
    (NULL, 'Protected MPEG-4 video file'),
    (NULL, 'Purchased AAC audio file'),
    (NULL, 'AAC audio file');

INSERT INTO genre VALUES
	(NULL, 'Rock'),
    (Null, 'Jazz'),
    (Null, 'Metal'),
    (Null, 'Alternative & Punk'),
    (Null, 'Rock And Roll'),
    (Null, 'Blues'),
    (Null, 'Latin'),
    (Null, 'Reggae'),
    (Null, 'Pop'),
    (Null, 'Soundtrack'),
    (Null, 'Bossa Nova'),
    (Null, 'Easy Listening'),
    (Null, 'Heavy Metal'),
    (Null, 'R&B/Soul'),
    (Null, 'Electronica/Dance'),
    (Null, 'World'),
    (Null, 'Hip Hop/Rap'),
    (Null, 'Science Fiction'),
    (Null, 'TV Shows'),
    (Null, 'Sci Fi & Fantasy'),
    (Null, 'Drama'),
    (Null, 'Comedy'),
    (Null, 'Alternative'),
    (Null, 'Classical'),
    (Null, 'Opera');

INSERT INTO playlist VALUES
	(NULL, 'Music'),
	(NULL, 'Movies'),
	(NULL, 'TV Shows'),
	(NULL, 'Audiobooks'),
	(NULL, "90's Music"),
	(NULL, 'Audiobooks'),
	(NULL, 'Movies'),
	(NULL, 'Music'),
	(NULL, 'Music Videos'),
	(NULL, 'TV Shows'),
	(NULL, 'Brazilian Music'),
	(NULL, 'Classical'),
	(NULL, 'Classical 101 - Deep Cuts'),
	(NULL, 'Classical 101 - Next Steps'),
	(NULL, 'Classical 101 - The Basics'),
	(NULL, 'Grunge'),
	(NULL, 'Heavy Metal Classic'),
	(NULL, 'On-The-Go 1');
    
INSERT INTO artist VALUES
	(NULL, "AC/DC"),
	(NULL, "Accept"),
	(NULL, "Aerosmith"),
	(NULL, "Alanis Morissette"),
	(NULL, "Alice In Chains"),
	(NULL, "Antônio Carlos Jobim"),
	(NULL, "Apocalyptica"),
	(NULL, "Audioslave"),
	(NULL, "BackBeat"),
	(NULL, "Billy Cobham"),
	(NULL, "Black Label Society"),
	(NULL, "Black Sabbath"),
	(NULL, "Body Count"),
	(NULL, "Bruce Dickinson"),
	(NULL, "Buddy Guy"),
	(NULL, "Caetano Veloso"),
	(NULL, "Chico Buarque"),
	(NULL, "Chico Science & Nação Zumbi"),
	(NULL, "Cidade Negra"),
	(NULL, "Cláudio Zoli"),
	(NULL, "Various Artists"),
	(NULL, "Led Zeppelin"),
	(NULL, "Frank Zappa & Captain Beefheart"),
	(NULL, "Marcos Valle"),
	(NULL, "Milton Nascimento & Bebeto"),
	(NULL, "Azymuth"),
	(NULL, "Gilberto Gil"),
	(NULL, "João Gilberto"),
	(NULL, "Bebel Gilberto"),
	(NULL, "Jorge Vercilo"),
	(NULL, "Baby Consuelo"),
	(NULL, "Ney Matogrosso"),
	(NULL, "Luiz Melodia"),
	(NULL, "Nando Reis"),
	(NULL, "Pedro Luís & A Parede"),
	(NULL, "O Rappa"),
	(NULL, "Ed Motta"),
	(NULL, "Banda Black Rio"),
	(NULL, "Fernanda Porto"),
	(NULL, "Os Cariocas"),
	(NULL, "Elis Regina"),
	(NULL, "Milton Nascimento"),
	(NULL, "A Cor Do Som"),
	(NULL, "Kid Abelha"),
	(NULL, "Sandra De Sá"),
	(NULL, "Jorge Ben"),
	(NULL, "Hermeto Pascoal"),
	(NULL, "Barão Vermelho"),
	(NULL, "Edson, DJ Marky & DJ Patife Featuring Fernanda Porto"),
	(NULL, "Metallica"),
	(NULL, "Queen"),
	(NULL, "Kiss"),
	(NULL, "Spyro Gyra"),
	(NULL, "Green Day"),
	(NULL, "David Coverdale"),
	(NULL, "Gonzaguinha"),
	(NULL, "Os Mutantes"),
	(NULL, "Deep Purple"),
	(NULL, "Santana"),
	(NULL, "Santana Feat. Dave Matthews"),
	(NULL, "Santana Feat. Everlast"),
	(NULL, "Santana Feat. Rob Thomas"),
	(NULL, "Santana Feat. Lauryn Hill & Cee-Lo"),
	(NULL, "Santana Feat. The Project G&B"),
	(NULL, "Santana Feat. Maná"),
	(NULL, "Santana Feat. Eagle-Eye Cherry"),
	(NULL, "Santana Feat. Eric Clapton"),
	(NULL, "Miles Davis"),
	(NULL, "Gene Krupa"),
	(NULL, "Toquinho & Vinícius"),
	(NULL, "Vinícius De Moraes & Baden Powell"),
	(NULL, "Vinícius De Moraes"),
	(NULL, "Vinícius E Qurteto Em Cy"),
	(NULL, "Vinícius E Odette Lara"),
	(NULL, "Vinicius, Toquinho & Quarteto Em Cy"),
	(NULL, "Creedence Clearwater Revival"),
	(NULL, "Cássia Eller"),
	(NULL, "Def Leppard"),
	(NULL, "Dennis Chambers"),
	(NULL, "Djavan"),
	(NULL, "Eric Clapton"),
	(NULL, "Faith No More"),
	(NULL, "Falamansa"),
	(NULL, "Foo Fighters"),
	(NULL, "Frank Sinatra"),
	(NULL, "Funk Como Le Gusta"),
	(NULL, "Godsmack"),
	(NULL, "Guns N' Roses"),
	(NULL, "Incognito"),
	(NULL, "Iron Maiden"),
	(NULL, "James Brown"),
	(NULL, "Jamiroquai"),
	(NULL, "JET"),
	(NULL, "Jimi Hendrix"),
	(NULL, "Joe Satriani"),
	(NULL, "Jota Quest"),
	(NULL, "João Suplicy"),
	(NULL, "Judas Priest"),
	(NULL, "Legião Urbana"),
	(NULL, "Lenny Kravitz"),
	(NULL, "Lulu Santos"),
	(NULL, "Marillion"),
	(NULL, "Marisa Monte"),
	(NULL, "Marvin Gaye"),
	(NULL, "Men At Work"),
	(NULL, "Motörhead"),
	(NULL, "Motörhead & Girlschool"),
	(NULL, "Mônica Marianno"),
	(NULL, "Mötley Crüe"),
	(NULL, "Nirvana"),
	(NULL, "O Terço"),
	(NULL, "Olodum"),
	(NULL, "Os Paralamas Do Sucesso"),
	(NULL, "Ozzy Osbourne"),
	(NULL, "Page & Plant"),
	(NULL, "Passengers"),
	(NULL, "Paul D'Ianno"),
	(NULL, "Pearl Jam"),
	(NULL, "Peter Tosh"),
	(NULL, "Pink Floyd"),
	(NULL, "Planet Hemp"),
	(NULL, "R.E.M. Feat. Kate Pearson"),
	(NULL, "R.E.M. Feat. KRS-One"),
	(NULL, "R.E.M."),
	(NULL, "Raimundos"),
	(NULL, "Raul Seixas"),
	(NULL, "Red Hot Chili Peppers"),
	(NULL, "Rush"),
	(NULL, "Simply Red"),
	(NULL, "Skank"),
	(NULL, "Smashing Pumpkins"),
	(NULL, "Soundgarden"),
	(NULL, "Stevie Ray Vaughan & Double Trouble"),
	(NULL, "Stone Temple Pilots"),
	(NULL, "System Of A Down"),
	(NULL, "Terry Bozzio, Tony Levin & Steve Stevens"),
	(NULL, "The Black Crowes"),
	(NULL, "The Clash"),
	(NULL, "The Cult"),
	(NULL, "The Doors"),
	(NULL, "The Police"),
	(NULL, "The Rolling Stones"),
	(NULL, "The Tea Party"),
	(NULL, "The Who"),
	(NULL, "Tim Maia"),
	(NULL, "Titãs"),
	(NULL, "Battlestar Galactica"),
	(NULL, "Heroes"),
	(NULL, "Lost"),
	(NULL, "U2"),
	(NULL, "UB40"),
	(NULL, "Van Halen"),
	(NULL, "Velvet Revolver"),
	(NULL, "Whitesnake"),
	(NULL, "Zeca Pagodinho"),
	(NULL, "The Office"),
	(NULL, "Dread Zeppelin"),
	(NULL, "Battlestar Galactica (Classic)"),
	(NULL, "Aquaman"),
	(NULL, "Christina Aguilera featuring BigElf"),
	(NULL, "Aerosmith & Sierra Leone's Refugee Allstars"),
	(NULL, "Los Lonely Boys"),
	(NULL, "Corinne Bailey Rae"),
	(NULL, "Dhani Harrison & Jakob Dylan"),
	(NULL, "Jackson Browne"),
	(NULL, "Avril Lavigne"),
	(NULL, "Big & Rich"),
	(NULL, "Youssou N'Dour"),
	(NULL, "Black Eyed Peas"),
	(NULL, "Jack Johnson"),
	(NULL, "Ben Harper"),
	(NULL, "Snow Patrol"),
	(NULL, "Matisyahu"),
	(NULL, "The Postal Service"),
	(NULL, "Jaguares"),
	(NULL, "The Flaming Lips"),
	(NULL, "Jack's Mannequin & Mick Fleetwood"),
	(NULL, "Regina Spektor"),
	(NULL, "Scorpions"),
	(NULL, "House Of Pain"),
	(NULL, "Xis"),
	(NULL, "Nega Gizza"),
	(NULL, "Gustavo & Andres Veiga & Salazar"),
	(NULL, "Rodox"),
	(NULL, "Charlie Brown Jr."),
	(NULL, "Pedro Luís E A Parede"),
	(NULL, "Los Hermanos"),
	(NULL, "Mundo Livre S/A"),
	(NULL, "Otto"),
	(NULL, "Instituto"),
	(NULL, "Nação Zumbi"),
	(NULL, "DJ Dolores & Orchestra Santa Massa"),
	(NULL, "Seu Jorge"),
	(NULL, "Sabotage E Instituto"),
	(NULL, "Stereo Maracana"),
	(NULL, "Cake"),
	(NULL, "Aisha Duo"),
	(NULL, "Habib Koité and Bamada"),
	(NULL, "Karsh Kale"),
	(NULL, "The Posies"),
	(NULL, "Luciana Souza/Romero Lubambo"),
	(NULL, "Aaron Goldberg"),
	(NULL, "Nicolaus Esterhazy Sinfonia"),
	(NULL, "Temple of the Dog"),
	(NULL, "Chris Cornell"),
	(NULL, "Alberto Turco & Nova Schola Gregoriana"),
	(NULL, "Richard Marlow & The Choir of Trinity College, Cambridge"),
	(NULL, "English Concert & Trevor Pinnock"),
	(NULL, "Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker"),
	(NULL, "Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer"),
	(NULL, "Wilhelm Kempff"),
	(NULL, "Yo-Yo Ma"),
	(NULL, "Scholars Baroque Ensemble"),
	(NULL, "Academy of St. Martin in the Fields & Sir Neville Marriner"),
	(NULL, "Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner"),
	(NULL, "Berliner Philharmoniker, Claudio Abbado & Sabine Meyer"),
	(NULL, "Royal Philharmonic Orchestra & Sir Thomas Beecham"),
	(NULL, "Orchestre Révolutionnaire et Romantique & John Eliot Gardiner"),
	(NULL, "Britten Sinfonia, Ivor Bolton & Lesley Garrett"),
	(NULL, "Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti"),
	(NULL, "Sir Georg Solti & Wiener Philharmoniker"),
	(NULL, "Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair"),
	(NULL, "London Symphony Orchestra & Sir Charles Mackerras"),
	(NULL, "Barry Wordsworth & BBC Concert Orchestra"),
	(NULL, "Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker"),
	(NULL, "Eugene Ormandy"),
	(NULL, "Luciano Pavarotti"),
	(NULL, "Leonard Bernstein & New York Philharmonic"),
	(NULL, "Boston Symphony Orchestra & Seiji Ozawa"),
	(NULL, "Aaron Copland & London Symphony Orchestra"),
	(NULL, "Ton Koopman"),
	(NULL, "Sergei Prokofiev & Yuri Temirkanov"),
	(NULL, "Chicago Symphony Orchestra & Fritz Reiner"),
	(NULL, "Orchestra of The Age of Enlightenment"),
	(NULL, "Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra"),
	(NULL, "James Levine"),
	(NULL, "Berliner Philharmoniker & Hans Rosbaud"),
	(NULL, "Maurizio Pollini"),
	(NULL, "Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett"),
	(NULL, "Gustav Mahler"),
	(NULL, "Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos"),
	(NULL, "Edo de Waart & San Francisco Symphony"),
	(NULL, "Antal Doráti & London Symphony Orchestra"),
	(NULL, "Choir Of Westminster Abbey & Simon Preston"),
	(NULL, "Michael Tilson Thomas & San Francisco Symphony"),
	(NULL, "Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker"),
	(NULL, "The King's Singers"),
	(NULL, "Berliner Philharmoniker & Herbert Von Karajan"),
	(NULL, "Sir Georg Solti, Sumi Jo & Wiener Philharmoniker"),
	(NULL, "Christopher O'Riley"),
	(NULL, "Fretwork"),
	(NULL, "Amy Winehouse"),
	(NULL, "Calexico"),
	(NULL, "Otto Klemperer & Philharmonia Orchestra"),
	(NULL, "Yehudi Menuhin"),
	(NULL, "Philharmonia Orchestra & Sir Neville Marriner"),
	(NULL, "Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart"),
	(NULL, "Les Arts Florissants & William Christie"),
	(NULL, "The 12 Cellists of The Berlin Philharmonic"),
	(NULL, "Adrian Leaper & Doreen de Feis"),
	(NULL, "Roger Norrington, London Classical Players"),
	(NULL, "Charles Dutoit & L'Orchestre Symphonique de Montréal"),
	(NULL, "Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir"),
	(NULL, "Kent Nagano and Orchestre de l'Opéra de Lyon"),
	(NULL, "Julian Bream"),
	(NULL, "Martin Roscoe"),
	(NULL, "Göteborgs Symfoniker & Neeme Järvi"),
	(NULL, "Itzhak Perlman"),
	(NULL, "Michele Campanella"),
	(NULL, "Gerald Moore"),
	(NULL, "Mela Tenenbaum, Pro Musica Prague & Richard Kapp"),
	(NULL, "Emerson String Quartet"),
	(NULL, "C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu"),
	(NULL, "Nash Ensemble"),
	(NULL, "Philip Glass Ensemble");

INSERT INTO album VALUES
	(NULL, "For Those About To Rock We Salute You", 1),
	(NULL, "Balls to the Wall", 2),
	(NULL, "Restless and Wild", 2),
	(NULL, "Let There Be Rock", 1),
	(NULL, "Big Ones", 3),
	(NULL, "Jagged Little Pill", 4),
	(NULL, "Facelift", 5),
	(NULL, "Warner 25 Anos", 6),
	(NULL, "Plays Metallica By Four Cellos", 7),
	(NULL, "Audioslave", 8),
	(NULL, "Out Of Exile", 8),
	(NULL, "BackBeat Soundtrack", 9),
	(NULL, "The Best Of Billy Cobham", 10),
	(NULL, "Alcohol Fueled Brewtality Live! [Disc 1]", 11),
	(NULL, "Alcohol Fueled Brewtality Live! [Disc 2]", 11),
	(NULL, "Black Sabbath", 12),
	(NULL, "Black Sabbath Vol. 4 (Remaster)", 12),
	(NULL, "Body Count", 13),
	(NULL, "Chemical Wedding", 14),
	(NULL, "The Best Of Buddy Guy - The Millenium Collection", 15),
	(NULL, "Prenda Minha", 16),
	(NULL, "Sozinho Remix Ao Vivo", 16),
	(NULL, "Minha Historia", 17),
	(NULL, "Afrociberdelia", 18),
	(NULL, "Da Lama Ao Caos", 18),
	(NULL, "Acústico MTV [Live]", 19),
	(NULL, "Cidade Negra - Hits", 19),
	(NULL, "Na Pista", 20),
	(NULL, "Axé Bahia 2001", 21),
	(NULL, "BBC Sessions [Disc 1] [Live]", 22),
	(NULL, "Bongo Fury", 23),
	(NULL, "Carnaval 2001", 21),
	(NULL, "Chill: Brazil (Disc 1)", 24),
	(NULL, "Chill: Brazil (Disc 2)", 6),
	(NULL, "Garage Inc. (Disc 1)", 50),
	(NULL, "Greatest Hits II", 51),
	(NULL, "Greatest Kiss", 52),
	(NULL, "Heart of the Night", 53),
	(NULL, "International Superhits", 54),
	(NULL, "Into The Light", 55),
	(NULL, "Meus Momentos", 56),
	(NULL, "Minha História", 57),
	(NULL, "MK III The Final Concerts [Disc 1]", 58),
	(NULL, "Physical Graffiti [Disc 1]", 22),
	(NULL, "Sambas De Enredo 2001", 21),
	(NULL, "Supernatural", 59),
	(NULL, "The Best of Ed Motta", 37),
	(NULL, "The Essential Miles Davis [Disc 1]", 68),
	(NULL, "The Essential Miles Davis [Disc 2]", 68),
	(NULL, "The Final Concerts (Disc 2)", 58),
	(NULL, "Up An' Atom", 69),
	(NULL, "Vinícius De Moraes - Sem Limite", 70),
	(NULL, "Vozes do MPB", 21),
	(NULL, "Chronicle, Vol. 1", 76),
	(NULL, "Chronicle, Vol. 2", 76),
	(NULL, "Cássia Eller - Coleção Sem Limite [Disc 2]", 77),
	(NULL, "Cássia Eller - Sem Limite [Disc 1]", 77),
	(NULL, "Come Taste The Band", 58),
	(NULL, "Deep Purple In Rock", 58),
	(NULL, "Fireball", 58),
	(NULL, "Knocking at Your Back Door: The Best Of Deep Purple in the 80's", 58),
	(NULL, "Machine Head", 58),
	(NULL, "Purpendicular", 58),
	(NULL, "Slaves And Masters", 58),
	(NULL, "Stormbringer", 58),
	(NULL, "The Battle Rages On", 58),
	(NULL, "Vault: Def Leppard's Greatest Hits", 78),
	(NULL, "Outbreak", 79),
	(NULL, "Djavan Ao Vivo - Vol. 02", 80),
	(NULL, "Djavan Ao Vivo - Vol. 1", 80),
	(NULL, "Elis Regina-Minha História", 41),
	(NULL, "The Cream Of Clapton", 81),
	(NULL, "Unplugged", 81),
	(NULL, "Album Of The Year", 82),
	(NULL, "Angel Dust", 82),
	(NULL, "King For A Day Fool For A Lifetime", 82),
	(NULL, "The Real Thing", 82),
	(NULL, "Deixa Entrar", 83),
	(NULL, "In Your Honor [Disc 1]", 84),
	(NULL, "In Your Honor [Disc 2]", 84),
	(NULL, "One By One", 84),
	(NULL, "The Colour And The Shape", 84),
	(NULL, "My Way: The Best Of Frank Sinatra [Disc 1]", 85),
	(NULL, "Roda De Funk", 86),
	(NULL, "As Canções de Eu Tu Eles", 27),
	(NULL, "Quanta Gente Veio Ver (Live)", 27),
	(NULL, "Quanta Gente Veio ver--Bônus De Carnaval", 27),
	(NULL, "Faceless", 87),
	(NULL, "American Idiot", 54),
	(NULL, "Appetite for Destruction", 88),
	(NULL, "Use Your Illusion I", 88),
	(NULL, "Use Your Illusion II", 88),
	(NULL, "Blue Moods", 89),
	(NULL, "A Matter of Life and Death", 90),
	(NULL, "A Real Dead One", 90),
	(NULL, "A Real Live One", 90),
	(NULL, "Brave New World", 90),
	(NULL, "Dance Of Death", 90),
	(NULL, "Fear Of The Dark", 90),
	(NULL, "Iron Maiden", 90),
	(NULL, "Killers", 90),
	(NULL, "Live After Death", 90),
	(NULL, "Live At Donington 1992 (Disc 1)", 90),
	(NULL, "Live At Donington 1992 (Disc 2)", 90),
	(NULL, "No Prayer For The Dying", 90),
	(NULL, "Piece Of Mind", 90),
	(NULL, "Powerslave", 90),
	(NULL, "Rock In Rio [CD1]", 90),
	(NULL, "Rock In Rio [CD2]", 90),
	(NULL, "Seventh Son of a Seventh Son", 90),
	(NULL, "Somewhere in Time", 90),
	(NULL, "The Number of The Beast", 90),
	(NULL, "The X Factor", 90),
	(NULL, "Virtual XI", 90),
	(NULL, "Sex Machine", 91),
	(NULL, "Emergency On Planet Earth", 92),
	(NULL, "Synkronized", 92),
	(NULL, "The Return Of The Space Cowboy", 92),
	(NULL, "Get Born", 93),
	(NULL, "Are You Experienced?", 94),
	(NULL, "Surfing with the Alien (Remastered)", 95),
	(NULL, "Jorge Ben Jor 25 Anos", 46),
	(NULL, "Jota Quest-1995", 96),
	(NULL, "Cafezinho", 97),
	(NULL, "Living After Midnight", 98),
	(NULL, "Unplugged [Live]", 52),
	(NULL, "BBC Sessions [Disc 2] [Live]", 22),
	(NULL, "Coda", 22),
	(NULL, "Houses Of The Holy", 22),
	(NULL, "In Through The Out Door", 22),
	(NULL, "IV", 22),
	(NULL, "Led Zeppelin I", 22),
	(NULL, "Led Zeppelin II", 22),
	(NULL, "Led Zeppelin III", 22),
	(NULL, "Physical Graffiti [Disc 2]", 22),
	(NULL, "Presence", 22),
	(NULL, "The Song Remains The Same (Disc 1)", 22),
	(NULL, "The Song Remains The Same (Disc 2)", 22),
	(NULL, "A TempestadeTempestade Ou O Livro Dos Dias", 99),
	(NULL, "Mais Do Mesmo", 99),
	(NULL, "Greatest Hits", 100),
	(NULL, "Lulu Santos - RCA 100 Anos De Música - Álbum 01", 101),
	(NULL, "Lulu Santos - RCA 100 Anos De Música - Álbum 02", 101),
	(NULL, "Misplaced Childhood", 102),
	(NULL, "Barulhinho Bom", 103),
	(NULL, "Seek And Shall Find: More Of The Best (1963-1981)", 104),
	(NULL, "The Best Of Men At Work", 105),
	(NULL, "Black Album", 50),
	(NULL, "Garage Inc. (Disc 2)", 50),
	(NULL, "Kill 'Em All", 50),
	(NULL, "Load", 50),
	(NULL, "Master Of Puppets", 50),
	(NULL, "ReLoad", 50),
	(NULL, "Ride The Lightning", 50),
	(NULL, "St. Anger", 50),
	(NULL, "...And Justice For All", 50),
	(NULL, "Miles Ahead", 68),
	(NULL, "Milton Nascimento Ao Vivo", 42),
	(NULL, "Minas", 42),
	(NULL, "Ace Of Spades", 106),
	(NULL, "Demorou...", 108),
	(NULL, "Motley Crue Greatest Hits", 109),
	(NULL, "From The Muddy Banks Of The Wishkah [Live]", 110),
	(NULL, "Nevermind", 110),
	(NULL, "Compositores", 111),
	(NULL, "Olodum", 112),
	(NULL, "Acústico MTV", 113),
	(NULL, "Arquivo II", 113),
	(NULL, "Arquivo Os Paralamas Do Sucesso", 113),
	(NULL, "Bark at the Moon (Remastered)", 114),
	(NULL, "Blizzard of Ozz", 114),
	(NULL, "Diary of a Madman (Remastered)", 114),
	(NULL, "No More Tears (Remastered)", 114),
	(NULL, "Tribute", 114),
	(NULL, "Walking Into Clarksdale", 115),
	(NULL, "Original Soundtracks 1", 116),
	(NULL, "The Beast Live", 117),
	(NULL, "Live On Two Legs [Live]", 118),
	(NULL, "Pearl Jam", 118),
	(NULL, "Riot Act", 118),
	(NULL, "Ten", 118),
	(NULL, "Vs.", 118),
	(NULL, "Dark Side Of The Moon", 120),
	(NULL, "Os Cães Ladram Mas A Caravana Não Pára", 121),
	(NULL, "Greatest Hits I", 51),
	(NULL, "News Of The World", 51),
	(NULL, "Out Of Time", 122),
	(NULL, "Green", 124),
	(NULL, "New Adventures In Hi-Fi", 124),
	(NULL, "The Best Of R.E.M.: The IRS Years", 124),
	(NULL, "Cesta Básica", 125),
	(NULL, "Raul Seixas", 126),
	(NULL, "Blood Sugar Sex Magik", 127),
	(NULL, "By The Way", 127),
	(NULL, "Californication", 127),
	(NULL, "Retrospective I (1974-1980)", 128),
	(NULL, "Santana - As Years Go By", 59),
	(NULL, "Santana Live", 59),
	(NULL, "Maquinarama", 130),
	(NULL, "O Samba Poconé", 130),
	(NULL, "Judas 0: B-Sides and Rarities", 131),
	(NULL, "Rotten Apples: Greatest Hits", 131),
	(NULL, "A-Sides", 132),
	(NULL, "Morning Dance", 53),
	(NULL, "In Step", 133),
	(NULL, "Core", 134),
	(NULL, "Mezmerize", 135),
	(NULL, "[1997] Black Light Syndrome", 136),
	(NULL, "Live [Disc 1]", 137),
	(NULL, "Live [Disc 2]", 137),
	(NULL, "The Singles", 138),
	(NULL, "Beyond Good And Evil", 139),
	(NULL, "Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]", 139),
	(NULL, "The Doors", 140),
	(NULL, "The Police Greatest Hits", 141),
	(NULL, "Hot Rocks, 1964-1971 (Disc 1)", 142),
	(NULL, "No Security", 142),
	(NULL, "Voodoo Lounge", 142),
	(NULL, "Tangents", 143),
	(NULL, "Transmission", 143),
	(NULL, "My Generation - The Very Best Of The Who", 144),
	(NULL, "Serie Sem Limite (Disc 1)", 145),
	(NULL, "Serie Sem Limite (Disc 2)", 145),
	(NULL, "Acústico", 146),
	(NULL, "Volume Dois", 146),
	(NULL, "Battlestar Galactica: The Story So Far", 147),
	(NULL, "Battlestar Galactica, Season 3", 147),
	(NULL, "Heroes, Season 1", 148),
	(NULL, "Lost, Season 3", 149),
	(NULL, "Lost, Season 1", 149),
	(NULL, "Lost, Season 2", 149),
	(NULL, "Achtung Baby", 150),
	(NULL, "All That You Can't Leave Behind", 150),
	(NULL, "B-Sides 1980-1990", 150),
	(NULL, "How To Dismantle An Atomic Bomb", 150),
	(NULL, "Pop", 150),
	(NULL, "Rattle And Hum", 150),
	(NULL, "The Best Of 1980-1990", 150),
	(NULL, "War", 150),
	(NULL, "Zooropa", 150),
	(NULL, "UB40 The Best Of - Volume Two [UK]", 151),
	(NULL, "Diver Down", 152),
	(NULL, "The Best Of Van Halen, Vol. I", 152),
	(NULL, "Van Halen", 152),
	(NULL, "Van Halen III", 152),
	(NULL, "Contraband", 153),
	(NULL, "Vinicius De Moraes", 72),
	(NULL, "Ao Vivo [IMPORT]", 155),
	(NULL, "The Office, Season 1", 156),
	(NULL, "The Office, Season 2", 156),
	(NULL, "The Office, Season 3", 156),
	(NULL, "Un-Led-Ed", 157),
	(NULL, "Battlestar Galactica (Classic), Season 1", 158),
	(NULL, "Aquaman", 159),
	(NULL, "Instant Karma: The Amnesty International Campaign to Save Darfur", 150),
	(NULL, "Speak of the Devil", 114),
	(NULL, "20th Century Masters - The Millennium Collection: The Best of Scorpions", 179),
	(NULL, "House of Pain", 180),
	(NULL, "Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro", 36),
	(NULL, "Cake: B-Sides and Rarities", 196),
	(NULL, "LOST, Season 4", 149),
	(NULL, "Quiet Songs", 197),
	(NULL, "Muso Ko", 198),
	(NULL, "Realize", 199),
	(NULL, "Every Kind of Light", 200),
	(NULL, "Duos II", 201),
	(NULL, "Worlds", 202),
	(NULL, "The Best of Beethoven", 203),
	(NULL, "Temple of the Dog", 204),
	(NULL, "Carry On", 205),
	(NULL, "Revelations", 8),
	(NULL, "Adorate Deum: Gregorian Chant from the Proper of the Mass", 206),
	(NULL, "Allegri: Miserere", 207),
	(NULL, "Pachelbel: Canon & Gigue", 208),
	(NULL, "Vivaldi: The Four Seasons", 209),
	(NULL, "Bach: Violin Concertos", 210),
	(NULL, "Bach: Goldberg Variations", 211),
	(NULL, "Bach: The Cello Suites", 212),
	(NULL, "Handel: The Messiah (Highlights)", 213),
	(NULL, "The World of Classical Favourites", 214),
	(NULL, "Sir Neville Marriner: A Celebration", 215),
	(NULL, "Mozart: Wind Concertos", 216),
	(NULL, "Haydn: Symphonies 99 - 104", 217),
	(NULL, "Beethoven: Symhonies Nos. 5 & 6", 218),
	(NULL, "A Soprano Inspired", 219),
	(NULL, "Great Opera Choruses", 220),
	(NULL, "Wagner: Favourite Overtures", 221),
	(NULL, "Fauré: Requiem, Ravel: Pavane & Others", 222),
	(NULL, "Tchaikovsky: The Nutcracker", 223),
	(NULL, "The Last Night of the Proms", 224),
	(NULL, "Puccini: Madama Butterfly - Highlights", 225),
	(NULL, "Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies", 226),
	(NULL, "Pavarotti's Opera Made Easy", 227),
	(NULL, "Great Performances - Barber's Adagio and Other Romantic Favorites for Strings", 228),
	(NULL, "Carmina Burana", 229),
	(NULL, "A Copland Celebration, Vol. I", 230),
	(NULL, "Bach: Toccata & Fugue in D Minor", 231),
	(NULL, "Prokofiev: Symphony No.1", 232),
	(NULL, "Scheherazade", 233),
	(NULL, "Bach: The Brandenburg Concertos", 234),
	(NULL, "Chopin: Piano Concertos Nos. 1 & 2", 235),
	(NULL, "Mascagni: Cavalleria Rusticana", 236),
	(NULL, "Sibelius: Finlandia", 237),
	(NULL, "Beethoven Piano Sonatas: Moonlight & Pastorale", 238),
	(NULL, "Great Recordings of the Century - Mahler: Das Lied von der Erde", 240),
	(NULL, "Elgar: Cello Concerto & Vaughan Williams: Fantasias", 241),
	(NULL, "Adams, John: The Chairman Dances", 242),
	(NULL, "Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory", 243),
	(NULL, "Palestrina: Missa Papae Marcelli & Allegri: Miserere", 244),
	(NULL, "Prokofiev: Romeo & Juliet", 245),
	(NULL, "Strauss: Waltzes", 226),
	(NULL, "Berlioz: Symphonie Fantastique", 245),
	(NULL, "Bizet: Carmen Highlights", 246),
	(NULL, "English Renaissance", 247),
	(NULL, "Handel: Music for the Royal Fireworks (Original Version 1749)", 208),
	(NULL, "Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande", 248),
	(NULL, "Mozart Gala: Famous Arias", 249),
	(NULL, "SCRIABIN: Vers la flamme", 250),
	(NULL, "Armada: Music from the Courts of England and Spain", 251),
	(NULL, "Mozart: Symphonies Nos. 40 & 41", 248),
	(NULL, "Back to Black", 252),
	(NULL, "Frank", 252),
	(NULL, "Carried to Dust (Bonus Track Version)", 253),
	(NULL, "Beethoven: Symphony No. 6 'Pastoral' Etc.", 254),
	(NULL, "Bartok: Violin & Viola Concertos", 255),
	(NULL, "Mendelssohn: A Midsummer Night's Dream", 256),
	(NULL, "Bach: Orchestral Suites Nos. 1 - 4", 257),
	(NULL, "Charpentier: Divertissements, Airs & Concerts", 258),
	(NULL, "South American Getaway", 259),
	(NULL, "Górecki: Symphony No. 3", 260),
	(NULL, "Purcell: The Fairy Queen", 261),
	(NULL, "The Ultimate Relexation Album", 262),
	(NULL, "Purcell: Music for the Queen Mary", 263),
	(NULL, "Weill: The Seven Deadly Sins", 264),
	(NULL, "J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro", 265),
	(NULL, "Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps", 248),
	(NULL, "Szymanowski: Piano Works, Vol. 1", 266),
	(NULL, "Nielsen: The Six Symphonies", 267),
	(NULL, "Great Recordings of the Century: Paganini's 24 Caprices", 268),
	(NULL, "Liszt - 12 Études D'Execution Transcendante", 269),
	(NULL, "Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder", 270),
	(NULL, "Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3", 271),
	(NULL, "Respighi:Pines of Rome", 226),
	(NULL, "Schubert: The Late String Quartets & String Quintet (3 CD's)", 272),
	(NULL, "Monteverdi: L'Orfeo", 273),
	(NULL, "Mozart: Chamber Music", 274),
	(NULL, "Koyaanisqatsi (Soundtrack from the Motion Picture)", 275);

USE chinook;

SELECT
	ar.name,
	al.title
FROM album al
	INNER JOIN artist ar ON ar.artist_id = al.artist_id
WHERE ar.name LIKE '%morissette%'
-- SELECT * FROM artist;
-- SELECT * FROM album WHERE artist_id = 4;

-- TODO: test a deletion to see if cascading is working